### ISSUE TITLE
Uncaught Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by musana** [pghilardi/atom-python-virtualenv#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Ubuntu 14.04.5
**Thrown From**: [atom-python-virtualenv](https://github.com/pghilardi/atom-python-virtualenv) package 0.6.0

### Stack Trace

Uncaught Error: spawn ENOTDIR

```
At internal/child_process.js:313

Error: spawn ENOTDIR
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:392:9)
    at Object.exports.execFile (child_process.js:155:15)
    at Object.module.(anonymous function) [as execFile] (ELECTRON_ASAR.js:195:20)
    at exports.exec (child_process.js:115:18)
    at childProcess.(anonymous function) (ELECTRON_ASAR.js:680:22)
    at VirtualenvManager.module.exports.VirtualenvManager.get_options (/packages/atom-python-virtualenv/lib/virtualenv-manager.coffee:76:7)
    at VirtualenvManager.module.exports.VirtualenvManager.setup (/packages/atom-python-virtualenv/lib/virtualenv-manager.coffee:49:8)
    at /packages/atom-python-virtualenv/lib/virtualenv-manager.coffee:29:12
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19)
```

### Commands

```
     -2:37.9.0 core:confirm (input.hidden-input)
     -1:49.2.0 core:select-all (input.hidden-input)
     -1:45.2.0 core:backspace (input.hidden-input)
  3x -1:44.8.0 core:confirm (input.hidden-input)
 12x -1:11.5.0 core:backspace (input.hidden-input)
     -0:34.9.0 core:select-all (input.hidden-input)
     -0:33.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-django 0.3.2 
atom-python-virtualenv 0.6.0 
autocomplete-python 1.8.57 
django-templates 0.5.0 
```

**Comment by pghilardi** [comment]
@musana,

Could you give me more information about how you reproduced this bug?

**Comment by pghilardi** [comment]
@musana ,

Update to the last version 0.11.0 and this bug probably is solved.
