### ISSUE TITLE
Uncaught TypeError: path.join is not a function

### ISSUE THREAD

**Issue by RAbraham** [pghilardi/atom-python-virtualenv#14]
Steps:
1) Try to edit the project path in the settings using the backspace key.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [atom-python-virtualenv](https://github.com/pghilardi/atom-python-virtualenv) package 0.9.0

### Stack Trace

Uncaught TypeError: path.join is not a function

```
At /Users/rajivabraham/.atom/packages/atom-python-virtualenv/lib/virtualenv-manager.coffee:75

TypeError: path.join is not a function
  at /packages/atom-python-virtualenv/lib/virtualenv-manager.coffee:75:37
  at ChildProcess.exithandler (child_process.js:209:7)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at maybeClose (internal/child_process.js:877:16)
  at Socket.<anonymous> (internal/child_process.js:334:11)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at Pipe._handle.close [as _onclose] (net.js:493:12)

```

### Commands

```
     -3:56.4.0 core:confirm (input.hidden-input)
     -3:54.2.0 command-palette:toggle (input.hidden-input)
     -3:52.2.0 editor:move-to-first-character-of-line (input.hidden-input)
     -3:50.4.0 core:confirm (input.hidden-input)
     -3:50.4.0 virtualenv:select (input.hidden-input)
     -3:48.7.0 core:backspace (input.hidden-input)
     -3:48.2.0 editor:consolidate-selections (input.hidden-input)
     -3:48.2.0 core:cancel (input.hidden-input)
     -3:46.9.0 command-palette:toggle (input.hidden-input)
     -3:44.7.0 core:confirm (input.hidden-input)
     -3:44.7.0 virtualenv:select (input.hidden-input)
     -3:43.3.0 editor:consolidate-selections (input.hidden-input)
     -3:43.3.0 core:cancel (input.hidden-input)
     -3:43.1.0 editor:consolidate-selections (input.hidden-input)
     -3:43.1.0 core:cancel (input.hidden-input)
     -0:14.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-python-virtualenv 0.9.0 
atom-runner 2.7.1 
autocomplete-haskell 0.7.2 
autocomplete-python 1.8.60 
haskell-debug 0.2.1 
haskell-ghc-mod 1.19.9 
haskell-pointfree 0.2.0 
ide-haskell 1.9.6 
ide-haskell-cabal 1.9.2 
ide-haskell-hasktags 0.0.10 
ide-haskell-hoogle 0.0.6 
ide-haskell-repl 0.6.0 
ide-purescript 0.15.3 
language-haskell 1.12.1 
language-haskell-scoped 0.0.4 
language-purescript 0.8.2 
linter 1.11.23 
markdown-preview-plus 2.4.9 
markdown-writer 2.6.4 
nuclide 0.209.0 
python-tools 0.6.9 
script 3.14.1 
tasks 2.6.6 
```

**Comment by pghilardi** [comment]
@RAbraham, I have fixed this issue now in the version 0.0.10. Thanks!
