### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by marcelhekking** [pghilardi/atom-python-virtualenv#15]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.10
**Thrown From**: [atom-python-virtualenv](https://github.com/pghilardi/atom-python-virtualenv) package 0.9.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of null

```
At /home/marcel/Dropbox/Atom/packages/atom-python-virtualenv/lib/virtualenv-manager.coffee:85

TypeError: Cannot read property 'path' of null
    at VirtualenvManager.module.exports.VirtualenvManager.getPathForEnv (/packages/atom-python-virtualenv/lib/virtualenv-manager.coffee:85:17)
    at VirtualenvManager.module.exports.VirtualenvManager.deactivate (/packages/atom-python-virtualenv/lib/virtualenv-manager.coffee:99:52)
    at /packages/atom-python-virtualenv/lib/init.coffee:55:15)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at Object.didConfirmSelection (/app.asar/node_modules/command-palette/lib/command-palette-view.js:106:29)
    at SelectListView.confirmSelection (/app.asar/node_modules/atom-select-list/src/select-list-view.js:292:20)
    at /app.asar/node_modules/atom-select-list/src/select-list-view.js:64:14)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  2x -0:49 core:move-down (input.hidden-input)
     -0:48.1.0 core:confirm (input.hidden-input)
     -0:48.1.0 virtualenv:deactivate (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:43.7.0 intentions:highlight (input.hidden-input)
     -0:29.5.0 core:move-up (input.hidden-input)
  2x -0:29.1.0 core:backspace (input.hidden-input)
     -0:28.2.0 intentions:highlight (input.hidden-input)
     -0:27.8.0 core:save (input.hidden-input)
     -0:27.1.0 core:backspace (input.hidden-input)
     -0:27 intentions:highlight (input.hidden-input)
     -0:27 core:save (input.hidden-input)
  3x -0:25.4.0 core:move-down (input.hidden-input)
     -0:15.6.0 command-palette:toggle (atom-pane.pane.active)
  2x -0:12.8.0 core:move-down (input.hidden-input)
     -0:11.5.0 core:confirm (input.hidden-input)
     -0:11.5.0 virtualenv:deactivate (atom-pane.pane.active)
```

### Non-Core Packages

```
atom-python-virtualenv 0.9.0 
autocomplete-python 1.8.63 
blame 0.10.3 
busy-signal 1.4.1 
clipboard-plus 0.5.1 
django-templates 0.5.0 
expand-selection-to-quotes 0.11.0 
file-icons 2.1.4 
git-blame 1.0.1 
git-time-machine 1.5.9 
highlight-selected 0.13.1 
hyperclick 0.0.40 
indent-guide-improved 1.4.12 
indentation-jumper 0.1.2 
intentions 1.1.2 
language-ignore 1.5.2 
linter 2.1.4 
linter-annotations 1.0.1 
linter-flake8 2.2.1 
linter-htmlhint 1.3.3 
linter-ui-default 1.2.3 
local-history 4.0.1 
lorem 1.2.1 
MagicPython 1.0.9 
minimap 4.28.1 
minimap-cursorline 0.2.0 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
monokai 0.22.0 
monokai-seti 0.7.0 
navigation-history 0.1.8 
pdf-view 0.57.0 
pigments 0.39.1 
project-manager 3.3.4 
python-isort 0.0.7 
scroll-without-moving-cursor 0.3.5 
seti-ui 1.7.0 
Sublime-Style-Column-Selection 1.7.4 
symbols-view-plus 0.113.2-plus.4 
todo-show 1.11.0 
toggle-quotes 1.0.1 
wombat-light-syntax 1.2.0 
```

**Comment by pghilardi** [comment]
@marcelhekking  ,

I think that this bug was solved in the latest version: 0.11.0.

Could you check?

Thanks
