### ISSUE TITLE
Failed to activate the atom-python-virtualenv package

### ISSUE THREAD

**Issue by nabilr** [pghilardi/atom-python-virtualenv#21]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [atom-python-virtualenv](https://github.com/pghilardi/atom-python-virtualenv) package 0.14.0

### Stack Trace

Failed to activate the atom-python-virtualenv package

```
At Cannot read property 'getStatus' of undefined

TypeError: Cannot read property 'getStatus' of undefined
    at Object.consumeStatusBar (/packages/atom-python-virtualenv/lib/init.coffee:96:71)
    at Provider.module.exports.Provider.provide (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/service-hub/lib/provider.js:34:1)
    at ServiceHub.module.exports.ServiceHub.consume (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/service-hub/lib/service-hub.js:50:1)
    at Package.module.exports.Package.activateServices (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:454:1)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:256:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:99:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:642:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/package-manager.js:519:1
    at exit (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/settings-view/lib/package-manager.js:128:1)
    at triggerExitCallback (~/AppData/Local/atom/app-1.17.2/resources/app/src/buffered-process.js:338:1)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.17.2/resources/app/src/buffered-process.js:368:1)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -2:05.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-python-run 0.7.3 
atom-python-virtualenv 0.14.0 
autocomplete-python 1.8.63 
python-jedi 0.3.8 
python-tools 0.6.9 
```

**Comment by turagittech** [comment]
Had the problem today on a Windows 7 PC

**Comment by pghilardi** [comment]
This plug-in is not supported in Windows for now. I am accepting help to port it to Windows.
