### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by blacksoares** [pghilardi/atom-python-virtualenv#36]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Ubuntu 18.04
**Thrown From**: [atom-python-virtualenv](https://github.com/pghilardi/atom-python-virtualenv) package 1.0.2

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at /packages/atom-python-virtualenv/lib/virtualenv-manager.coffee:138:45
    at ChildProcess.exithandler (child_process.js:209:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
```

### Commands

```
     -0:22.8.0 command-palette:toggle (div.tool-panel.tree-view)
  2x -0:19.5.0 core:backspace (input.hidden-input)
     -0:16.5.0 core:confirm (input.hidden-input)
     -0:16.5.0 virtualenv:make (div.tool-panel.tree-view)
     -0:13.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-material-ui 2.1.3 
atom-python-virtualenv 1.0.2 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
city-lights-ui 1.3.3 
file-icons 2.1.19 
gcc-make-run 0.2.12 
git-control 0.9.0 
intentions 1.1.5 
linter 2.2.0 
linter-flake8 2.3.0 
linter-ui-default 1.7.1 
minimap 4.29.8 
platformio-ide-terminal 2.8.1 
python-autopep8 0.1.3 
script 3.17.3 
```

**Comment by mightydok** [comment]
+1
