### ISSUE TITLE
Path must be a string. Received undefined

### ISSUE THREAD

**Issue by mujicadiazr** [pghilardi/atom-python-virtualenv#5]
Hi there,

This bug was throw when I installed the extension on my Atom. 

`[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Microsoft Windows 10 Home
**Thrown From**: [atom-python-virtualenv](https://github.com/pghilardi/atom-python-virtualenv) package, v0.4.0

### Stack Trace

Failed to load the atom-python-virtualenv package

```
At Path must be a string. Received undefined

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:466:7)
    at new VirtualenvManager (file:///C:/Users/***/.atom/packages/atom-python-virtualenv/lib/virtualenv-manager.coffee:26:24)
    at Object.<anonymous> (file:///C:/Users/***/.atom/packages/atom-python-virtualenv/lib/init.coffee:7:16)
    at Object.<anonymous> (file:///C:/Users/***/.atom/packages/atom-python-virtualenv/lib/init.coffee:1:1)
    at Module._compile (C:\Users\***\AppData\Local\atom\app-1.12.7\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .coffee] (C:\Users\***\AppData\Local\atom\app-1.12.7\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\***\AppData\Local\atom\app-1.12.7\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\BlancaH\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:747:27)
    at C:\Users\***\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:118:28
    at Package.module.exports.Package.measure (C:\Users\***\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\***\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\***\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package-manager.js:468:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\***\AppData\Local\atom\app-1.12.7\resources\app.asar\src\package-manager.js:548:30)
    at C:\Users\***\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\settings-view\lib\package-manager.js:439:29
    at exit (C:\Users\***\AppData\Local\atom\app-1.12.7\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\***\AppData\Local\atom\app-1.12.7\resources\app.asar\src\buffered-process.js:215:47)
    at ChildProcess.<anonymous> (C:\Users\***\AppData\Local\atom\app-1.12.7\resources\app.asar\src\buffered-process.js:237:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
````

**Comment by pghilardi** [comment]
Hi @mujicadiazr,

The bug happened just on install or you tried to make or select a virtualenv?

**Comment by pghilardi** [comment]
@mujicadiazr ,

I have reproduced the problem and I am working to fix it.

**Comment by pghilardi** [comment]
Currently, this plug-in only works for linux. I am trying to make it work in windows, but I am having some problems replacing the path dynamically.

**Comment by pghilardi** [comment]
@mujicadiazr ,

I have closed this issue and created a new one to add full support to Windows in this package. I have some ideas on how to do this and tried to use the https://pypi.python.org/pypi/virtualenvwrapper-win project to use virtualenvwrapper in windows, but I am unable to persist changes to the PATH in Windows. It isn't working.

So, I am closing this issue and you can keep track in the new task to support Windows.
