### ISSUE TITLE
Failed to load the atom-python-virtualenv package

### ISSUE THREAD

**Issue by ranjian0** [pghilardi/atom-python-virtualenv#8]
[Enter steps to reproduce:]

1. Open Atom -> Settings -> Packages
2. Find package atom-python-virtualenv
3. Install Package.

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-python-virtualenv](https://github.com/pghilardi/atom-python-virtualenv) package 0.6.0

### Stack Trace

Failed to load the atom-python-virtualenv package

```
At Path must be a string. Received undefined

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:466:7)
    at /packages/atom-python-virtualenv/lib/virtualenv-manager.coffee:26:24)
    at /packages/atom-python-virtualenv/lib/init.coffee:7:16)
    at /packages/atom-python-virtualenv/lib/init.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:548:30)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:439:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:69:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:303:11)
    at /app.asar/src/buffered-process.js:333:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -5:31.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-python-package 0.7.0 
atom-python-run 0.7.3 
atom-python-virtualenv 0.6.0 
autocomplete-python 1.8.54 
python-debugger 0.2.0 
python-snippets 1.9.0 
python-tools 0.6.9 
```

**Comment by pghilardi** [comment]
@ranjian0 ,

This plug-in does not work with Windows.

**Comment by pghilardi** [comment]
I am closing this issue.

**Comment by AlexGluck** [comment]
Same error on linux fedora 25.

**Comment by pghilardi** [comment]
I will investigate this.@AlexGluck, are you using the version 1.0.2?

**Comment by AlexGluck** [comment]
yep

**Comment by pghilardi** [comment]
@AlexGluck ,

Could you paste the stack trace of this error on version 1.0.2?

**Comment by AlexGluck** [comment]
Ok, when i get again filed load extension i paste here. If after few month will not happen this close bug. Thx.

**Comment by iamh2o** [comment]
Hello from 2022.... aparently this bug is back, but note, I'm using the nightly build.




### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description



### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**



**Actual behavior:**



### Versions

**Atom**: 1.63.0-nightly1 x64
**Electron**: 11.5.0
**OS**: macOS 11.6.4
**Thrown From**: [atom-python-virtualenv](https://github.com/pghilardi/atom-python-virtualenv) package 1.0.4


### Stack Trace

Failed to load the atom-python-virtualenv package

```
At Cannot redefine property: length

TypeError: Cannot redefine property: length
    at Function.defineProperty (<anonymous>)
    at /app.asar/node_modules/oniguruma/src/oniguruma.js:108:8)
    at /app.asar/node_modules/oniguruma/src/oniguruma.js:116:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /app.asar/src/text-mate-language-mode.js:8:24)
    at /app.asar/src/text-mate-language-mode.js:1016:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /app.asar/src/text-editor.js:13:30)
    at /app.asar/src/text-editor.js:5857:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /app.asar/exports/atom.js:41:27)
    at /app.asar/exports/atom.js:46:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /packages/atom-python-virtualenv/lib/virtualenv-status-view.coffee:1:16)
    at /packages/atom-python-virtualenv/lib/virtualenv-status-view.coffee:1:1)
    at /packages/atom-python-virtualenv/lib/virtualenv-status-view.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at /packages/atom-python-virtualenv/lib/init.coffee:4:24)
    at /packages/atom-python-virtualenv/lib/init.coffee:1:1)
    at /packages/atom-python-virtualenv/lib/init.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:120:30)
    at /app.asar/src/compile-cache.js:252:23)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12633)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (/app.asar/src/native-compile-cache.js:67:27)
    at requireModule (/app.asar/src/module-utils.js:3:17)
    at Package.requireMainModule (/app.asar/src/package.js:909:27)
    at /app.asar/src/package.js:141:16
    at Package.measure (/app.asar/src/package.js:82:19)
    at Package.load (/app.asar/src/package.js:127:10)
    at PackageManager.loadAvailablePackage (/app.asar/src/package-manager.js:733:10)
    at PackageManager.loadPackage (/app.asar/src/package-manager.js:650:19)
    at PackageManager.activatePackage (/app.asar/src/package-manager.js:806:17)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:477:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:114:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:280:9)
    at /app.asar/src/buffered-process.js:310:9)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
advanced-railscasts-syntax 0.1.10 
alternatone-stark-sea-syntax 2.0.0 
asciidoc-assistant 0.2.3 
asciidoc-image-helper 1.0.1 
asciidoc-preview 2.13.1 
atom-black-syntax 0.34.0 
atom-black-ui 0.28.0 
atom-clock 0.1.18 
atom-drawio 1.15.0 
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.3 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.16.0 
atom-patternfly-syntax 1.1.0 
atom-patternfly-ui 6.0.0 
atom-python-virtualenv 1.0.4 
atomic-emacs 0.15.0 
atomic-terminal 1.1.7 
atrium-ui 0.2.2 
autocomplete-asciidoc 0.1.2 
blame 1.2.0 
busy-signal 2.0.1 
Chromo-Color-Previews 1.8.3 
cityscape-ui 1.5.0 
codyer-theme-syntax 0.4.0 
color-indent 1.1.0 
color-picker 2.3.0 
dark-side-of-the-moon-syntax 0.6.62 
emacs-tab 0.2.0 
failcoder-syntax 1.10.0 
firacode 0.3.0 
fusion-ui 0.13.0 
ghoulish-ui 1.1.3 
git-log 0.4.1 
git-menu 3.2.9 
git-plus 8.7.1 
git-split-diff-hyperclick 0.3.12 
git-time-machine 2.1.0 
hey-pane 1.2.0 
hitchhiker-neon-desert-ui 0.2.0 
hyperclick 0.1.5 
ide-r 0.1.8 
indent-guide-improved 1.4.13 
intentions 2.1.1 
juicy-syntax 1.0.5 
kite 0.206.0 
language-asciidoc 1.11.0 
language-emacs-lisp 1.4.1 
language-markdown 0.37.0 
linter 3.4.0 
linter-flake8 2.4.0 
linter-markdown 5.2.11 
linter-spell 0.15.0 
linter-stylelint 4.5.1 
linter-ui-default 3.4.1 
linter-write-good 0.9.3 
livestyle-atom 0.2.10 
markdown-commander 0.1.1 
markdown-document 0.2.1 
markdown-pdf 2.3.3 
markdown-preview-enhanced 0.19.2 
markdown-preview-plus 4.11.1 
markdown-to-pdf 0.1.1 
markdown-toc 0.4.2 
markdown-url-extract 1.2.0 
markdown-writer 2.11.12 
nebula-syntax 0.4.5 
nebula-ui 0.9.3 
neon-color-scheme 1.0.0 
nil-one-syntax 1.0.0 
nil-syntax 0.1.0 
nil-ui 0.2.0 
open-emacs 0.2.0 
open-in-ia-writer 0.0.1 
perspective-ui 0.11.0 
python-black 0.7.0 
python-docstring 0.0.3 
rbox 0.5.0 
sawyer-syntax 0.1.0 
sawyer-ui 0.2.0 
seti-bloody-syntax 0.2.2 
seti-icons 1.5.4 
SkriptDark-Syntax 2.1.2 
spell-check-project 0.7.2 
split-diff 1.6.1 
svg-icons 0.8.1 
sync-settings 5.2.16 
sync-settings-git-location 1.1.16 
Tech-Writer-IDE 0.2.0 
tiny-ui 3.0.0 
toggle-gutter 0.3.4 
tool-bar 1.4.4 
tool-bar-markdown-writer 0.5.1 
tree-view-menu 1.2.1 
TreeColor 1.0.6 
twenty-sleven-dark 0.2.0 
Tycho-Dark-Syntax 0.3.0 
typewriter-sounds 3.0.1 
ui 0.2.0 
url-utils 0.2.1 
vaporwave-ui 0.0.2 
xeta-syntax 0.5.0 
ymacs-editor 1.0.11 
zentabs 0.8.9 
Zeon-ui 0.3.0 
```

### Additional Information
